	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, RED
	tilepal 0, RED, RED, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, RED, BROWN, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, GRAY, WATER, WATER, GRAY, GREEN, GRAY, BROWN
	tilepal 0, BROWN, WATER, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, GRAY, GRAY, BROWN, GRAY, BROWN, BROWN, BROWN
	tilepal 0, WATER, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, RED, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, RED, RED, RED, ROOF, RED, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, RED, RED, RED
	tilepal 1, RED, ROOF, ROOF, ROOF, ROOF, ROOF, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, RED, RED, RED, WATER, WATER, WATER, RED
	tilepal 1, RED, RED, ROOF, RED, RED, ROOF, RED, RED
	tilepal 1, RED, ROOF, ROOF, RED, RED, RED, ROOF, ROOF
	tilepal 1, RED, RED, RED, RED, YELLOW, RED, GREEN, RED
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, RED, ROOF
