	tilepal 0, BROWN, ROOF, GRAY, GRAY, GREEN, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, BROWN, ROOF, GRAY, GRAY, WATER, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, TEXT
