	tilepal 0, GRAY, GRAY, GRAY, ROOF, GREEN, GREEN, GRAY, ROOF
	tilepal 0, RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GREEN, GRAY, BROWN
	tilepal 0, RED, RED, ROOF, ROOF, ROOF, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, BROWN, ROOF, ROOF, GRAY, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, GRAY, GRAY, GRAY, GRAY, BROWN, GRAY, BROWN
	tilepal 0, BROWN, WATER, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF
	tilepal 1, RED, RED, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, RED, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 1, GRAY, GRAY, GRAY, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 1, RED, RED, RED, YELLOW, YELLOW, RED, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, BROWN, ROOF, ROOF, ROOF, RED
	tilepal 1, GRAY, GRAY, GRAY, RED, BROWN, RED, RED, RED
	tilepal 1, RED, RED, RED, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, RED, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, RED
	tilepal 1, RED, WATER, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, BROWN, BROWN, GRAY, ROOF, ROOF, GREEN, RED
	tilepal 1, RED, RED, GRAY, GRAY, ROOF, GRAY, ROOF, GRAY
