	tilepal 0, GRAY, GRAY, GREEN, RED, GRAY, GREEN, GREEN, GRAY
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, WATER, WATER, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, YELLOW, YELLOW, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, GRAY, BROWN
	tilepal 0, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, TEXT

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT
