	tilepal 0, GRAY, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GREEN, GREEN, WATER, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, RED, RED, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY, GREEN
	tilepal 0, GREEN, GREEN, GREEN, RED, RED, WATER, GRAY, RED

rept 32
	db $ff
endr

	tilepal 1, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN